IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'Account' AND COLUMN_NAME = 'hwnd')
BEGIN
    ALTER TABLE Account ADD hwnd INT;
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'Account' AND COLUMN_NAME = 'threadID')
BEGIN
    ALTER TABLE Account ADD threadID INT;
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'Account' AND COLUMN_NAME = 'ProcessID')
BEGIN
    ALTER TABLE Account ADD ProcessID INT;
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'Account' AND COLUMN_NAME = 'WindowName')
BEGIN
    ALTER TABLE Account ADD WindowName NVARCHAR(255);
END;